### ISSUE TITLE
Add screenshot

### ISSUE THREAD

**Issue by KristjanESPERANTO** [thomo/MMM-kudos#1]
Thanks for the module! :slightly_smiling_face:

Can you add a screenshot directly to the repository? For example as `screenshot.png` or `example.png` in any folder.

This would have the advantage that the screenshot would be displayed in [the module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I am working on.

**Comment by KristjanESPERANTO** [comment]
@thomo Did you saw my request? :smiley:

**Comment by thomo** [comment]
@KristjanESPERANTO Please check, I added a screenshot. (Sorry for the delay.)

**Comment by KristjanESPERANTO** [comment]
Looks nice now :smiley: Thanks! :clap:
